# Generated by Django 6.0.2 on 2026-02-28 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('weighting', models.FloatField(help_text='Weighting of the assignment towards the final grade (e.g., 0.2 for 20%)')),
                ('grade', models.FloatField(blank=True, help_text='Grade received for the assignment (e.g., 85.5)', null=True)),
                ('time_needed', models.IntegerField(help_text='Estimated time needed to complete the assignment in minutes')),
                ('time_estimated', models.IntegerField(blank=True, help_text='Estimated time by ai complete the assignment in minutes', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Time spent on the assignment in minutes')),
                ('note', models.TextField(blank=True, help_text='Optional note of what was achieved', null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assignments.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note for the assignment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='assignments.assignment')),
            ],
        ),
    ]
