# Generated by Django 6.0.2 on 2026-02-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_created_at_assignment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlog',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Time spent on the assignment in minutes', null=True),
        ),
    ]
