# Generated by Django 6.0.2 on 2026-03-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignmentlog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='time_estimated',
            field=models.FloatField(blank=True, help_text='Estimated time by ai complete the assignment in hours', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='time_needed',
            field=models.FloatField(help_text='Estimated time needed to complete the assignment in hours'),
        ),
    ]
