# Generated by Django 6.0.2 on 2026-02-28 17:24

from django.db import migrations, models
from bustops.models import BusStop
import pandas as pd

def _trim_data(data):
    """ Trims the dataset provided to only necessary values """
    contents = []
    for row in data.iterrows():
        block = {"ATCOCode": row[1][1], 
                "Common_name": row[1][4], 
                "Indicator": row[1][14], 
                "Latitude": float(row[1][30]),
                "Longitude": float(row[1][29]),
                "Active": row[1][42]}
        
        if block["Active"] == "active":
            contents.append(block)
    
    return contents


def load_busstops(apps, schema_editor):

    bus_stop_raw_data = pd.read_csv("bus_stop_locations.csv")
    bus_stop_trimmed_data = _trim_data(bus_stop_raw_data)


    for busstop in bus_stop_trimmed_data:
        BusStop.objects.create(ATCOCode = busstop["ATCOCode"],
                               common_name = busstop["Common_name"],
                               indicator = busstop["Indicator"],
                               latitude = busstop["Latitude"],
                               longitude = busstop["Longitude"],
                               active = busstop["Active"])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATCOCode', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('indicator', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(load_busstops)
    ]
