# Generated by Django 6.0.2 on 2026-02-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('scheduled_time', models.CharField(max_length=255)),
                ('departure_time', models.CharField(max_length=255)),
                ('is_realtime', models.CharField(max_length=255)),
            ],
        ),
    ]
